### PR TITLE
FEM-1950: create empty .nomedia file in external storage->app->files

### PR DESCRIPTION
**Pull request by giladna**
This will prevent android will not index it

### CODE REVIEW

**Comment by giladna** [comment]
@noamtamim 
1.Need to make sure it is enough to have it in the root folder
2. Need to verify what about the ms4 extentios if this will filter indexing only for media files or also ts. files

**Comment by noamtamim** [comment]
@giladna Yes, nomedia is recursive, only one is needed (in the place you created it). 
It may be a good idea to allow apps to disable it in settings, WDYT?

**Comment by noamtamim** [comment]
It will cause the media scanner to skip the entire directory -- no files will be included (regardless of type).

**Comment by giladna** [comment]
@noamtamim 

adding it to settings is possible 
will add it

**Pull request merged**
