### PR TITLE
FEM-1952 Make directory creation more robust

### PR DESCRIPTION
**Pull request by noamtamim**
This shouldn't really be an issue, but in rare conditions directory creation seems to fail for unknown reasons. Added a retry mechanism and more explicit checks.

### CODE REVIEW

**Comment by vgaidarji** [comment]
@noamtamim thanks for taking care of this bug. 
Unfortunately, this is not a fix.

I have a physical device on which the issue with `mkdirs` is reproducible.
This is the device I'm using - https://www.phonearena.com/phones/Kyocera-Hydro-View_id9874.
It's not 100% of the times reproducible by having a deterministic pattern of steps to reproduce, but it can be reproduced in 6/10 or 7/10 cases.
Basically, what I'm doing is just installing the application on that device and at the moment when Kaltura DTG library tries to create directories, my application crashes. I can reinstall the application and crash will be there. I can clear application data from settings (which removes folders created by Kaltura), and crash is still there. I can install a previous version of my application where Kaltura DTG library version is <2.3.0, and crash is still there.
Then I can install application one more time, or simply reboot the device and crash disappears. **magic!** Then I play with application more (open/close it, clear data, reinstall the same version) and crash appears again and all consequent app launches will have the same crash related to `mkdirs`.

I've tried to identify what can go wrong and gather as much info as I was able to.

#### Build with Kaltura DTG 2.3.0 version

When I see the crash (first time or consequent times = doesn't matter), I see following errors in logs:

```
04-02 14:23:43.136 260-1437/? E/Vold: Failed to find mounted volume for /storage/sdcard1/Android/data/com.my.application.package/files/
04-02 11:40:34.958 2913-2913/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.my.application.package, PID: 2913
    java.lang.IllegalStateException: Can't continue without provider downloads -- /storage/emulated/0/Android/data/com.my.application.package/files/dtg/clear
        at com.kaltura.dtg.clear.DefaultDownloadService.a(DefaultDownloadService.java:325)
        at com.kaltura.dtg.clear.DefaultDownloadService.start(DefaultDownloadService.java:271)
        at com.kaltura.dtg.clear.h$1.onServiceConnected(DefaultProviderProxy.java:36)
        at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1208)
        at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1225)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5438)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:697)
```
and when I check the directories structure on device (via `adb shell`) I see this
```
-rw-rw---- root     sdcard_r        0 1970-01-02 21:41 .nomedia
drwxrwx--- u0_a44   sdcard_r          1970-01-02 21:41 com.android.browser
drwxrwx--- u0_a30   sdcard_r          2018-03-27 10:49 com.android.vending
drwxrwx--- u0_a114  sdcard_r          2018-04-02 11:40 com.my.application.package
drwxrwx--- u0_a57   sdcard_r          2018-03-27 10:51 com.google.android.apps.docs
drwxrwx--- u0_a74   sdcard_r          1970-01-02 21:41 com.google.android.apps.magazines
drwxrwx--- u0_a70   sdcard_r          1970-01-02 21:41 com.google.android.apps.maps
drwxrwx--- u0_a83   sdcard_r          2018-03-28 18:20 com.google.android.apps.photos
drwxrwx--- u0_a60   sdcard_r          2018-03-27 11:01 com.google.android.gm
drwxrwx--- u0_a18   sdcard_r          2018-03-27 10:37 com.google.android.gms
drwxrwx--- u0_a37   sdcard_r          1970-01-02 21:41 com.google.android.googlequicksearchbox
drwxrwx--- u0_a67   sdcard_r          2018-03-27 12:33 com.google.android.inputmethod.latin
drwxrwx--- u0_a73   sdcard_r          1970-01-02 21:42 com.google.android.music
drwxrwx--- u0_a91   sdcard_r          1970-01-02 21:42 com.google.android.videos
drwxrwx--- u0_a95   sdcard_r          1970-01-02 21:41 com.google.android.youtube
drwxrwx--- u0_a17   sdcard_r          1970-01-02 21:41 com.mobisystems.fileman
drwxrwx--- u0_a29   sdcard_r          2018-03-30 16:50 com.mobisystems.office
drwxrwx--- u0_a7    sdcard_r          1970-01-02 21:41 deezer.android.app
drwxrwx--- u0_a35   sdcard_r          1970-01-02 21:41 jp.kyocera.kyoceradrmgallery


shell@C6742:/mnt/sdcard/Android/data/com.my.application.package $ ls -al
drwxrwx--- u0_a114  sdcard_r          2018-04-02 11:40 files
shell@C6742:/mnt/sdcard/Android/data/com.my.application.package $ cd files
shell@C6742:/mnt/sdcard/Android/data/com.my.application.package/files $ ls -al
```
So `/mnt/sdcard/Android/data/com.my.application.package/files` path is present, but not full path `/mnt/sdcard/Android/data/com.my.application.package/files/dtg/clear`.

#### Build with Kaltura DTG from this PR (commit https://github.com/kaltura/playkit-dtg-android/commit/8897b0f29b8b06d79ed8aa3343d79fd34920595d) 

I checked out the Kaltura DTG from commit https://github.com/kaltura/playkit-dtg-android/commit/8897b0f29b8b06d79ed8aa3343d79fd34920595d locally, added Kaltura DTG as a module inside my project, and replicated the same crash.
Here're the errors from this test run:
```
04-02 14:38:34.626 260-1437/? E/cutils: Failed to fstatat(/mnt/shell/emulated/0/Android/data/com.my.application.package): Device or resource busy
04-02 14:38:34.636 260-1437/? E/Vold: Failed to find mounted volume for /storage/sdcard1/Android/data/com.my.application.package/files/
04-02 14:38:38.746 9905-9905/com.my.application.package E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.my.application.package, PID: 9905
    com.kaltura.dtg.clear.DefaultDownloadService$CannotCreateDirectoryException: Unknown reason; /storage/emulated/0/Android/data/com.my.application.package/files/dtg/clear
        at com.kaltura.dtg.clear.DefaultDownloadService.a(DefaultDownloadService.java:353)
        at com.kaltura.dtg.clear.DefaultDownloadService.start(DefaultDownloadService.java:271)
        at com.kaltura.dtg.clear.h$1.onServiceConnected(DefaultProviderProxy.java:36)
        at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1208)
        at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1225)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5438)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:697)
```

💡 Directories structure and rights are the same as from the previous step where Kaltura DTG 2.3.0 was used.

#### Logs from successful run
Providing logs from the case when the application starts just fine and `dtg/clear` directories created with no issues. 
⚠️ I've got the application crashing case, after that cleared out the logs, reinstalled the application (with Kaltura 2.3.0 DTG) and no crash occured. Nothing more, just these steps.
```
04-02 15:07:56.676 729-2831/? E/WifiStateMachine: WifiStateMachine CMD_START_SCAN source -2 txSuccessRate=3.25 rxSuccessRate=22.00 targetRoamBSSID=any RSSI=-65
04-02 15:08:16.676 729-2831/? E/WifiStateMachine: WifiStateMachine CMD_START_SCAN source -2 txSuccessRate=1.20 rxSuccessRate=18.95 targetRoamBSSID=any RSSI=-60
04-02 15:08:25.426 3298-3410/? E/ExternalAccountType: Unsupported attribute readOnly
04-02 15:08:25.776 6107-6107/? E/Finsky: [1] com.google.android.finsky.wear.au.a(3): onConnectionFailed: ConnectionResult{statusCode=API_UNAVAILABLE, resolution=null, message=null}
04-02 15:08:25.966 3660-3660/? E/AppsCustomizePagedView: Failed to get the system property.. key:rw_launcher_reset_order
    java.lang.SecurityException
        at android.os.Parcel.readException(Parcel.java:1546)
        at android.os.Parcel.readException(Parcel.java:1499)
        at jp.kyocera.internal.clomask.ITransferService$Stub$Proxy.get(ITransferService.java:107)
        at jp.kyocera.internal.clomask.Transfer.get(Transfer.java:178)
        at jp.kyocera.kyocerahome.launcher.AppsCustomizePagedView.isResetOrderComplete(AppsCustomizePagedView.java:6455)
        at jp.kyocera.kyocerahome.launcher.AppsCustomizePagedView.addAppsWithoutInvalidate(AppsCustomizePagedView.java:2702)
        at jp.kyocera.kyocerahome.launcher.AppsCustomizePagedView.addApps(AppsCustomizePagedView.java:2754)
        at jp.kyocera.kyocerahome.launcher.Launcher.bindAppsAdded(Launcher.java:7645)
        at jp.kyocera.kyocerahome.launcher.LauncherModel$PackageUpdatedTask$1.run(LauncherModel.java:3807)
        at jp.kyocera.kyocerahome.launcher.DeferredHandler$Impl.handleMessage(DeferredHandler.java:51)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5438)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:697)
04-02 15:08:36.686 729-2831/? E/WifiStateMachine: WifiStateMachine CMD_START_SCAN source -2 txSuccessRate=7.71 rxSuccessRate=42.36 targetRoamBSSID=any RSSI=-61
04-02 15:08:49.626 260-1437/? E/cutils: Failed to fstatat(/mnt/shell/emulated/0/Android/data/com.my.application.package): Device or resource busy
04-02 15:08:49.636 260-1437/? E/Vold: Failed to find mounted volume for /storage/sdcard1/Android/data/com.my.application.package/files/
04-02 15:08:52.916 11758-11877/? E/ActivityThread: Failed to find provider info for com.facebook.katana.provider.AttributionIdProvider
04-02 15:08:53.576 11758-11758/? E/MediaPlayer-JNI: QCMediaPlayer mediaplayer NOT present
04-02 15:08:53.586 262-2879/? E/MediaPlayerFactory: getPlayerType : fd =48 fileDesc=54
    getPlayerType : failed to open file by handle, result = 16
    getPlayerType() : failed to get mime type, result = 16
04-02 15:08:53.586 262-2879/? E/DrmManagerClientWrapperImpl: DrmManagerClientSubWrapper::DrmInitialization()
04-02 15:08:53.596 330-330/? E/DxDrmPluginEngine: DxDrmFrameworkPlugin::getDecodeSession : decryptSession not found
04-02 15:08:53.596 330-330/? E/DxDrmPluginEngine: DxDrmFrameworkPlugin::onOpenDecryptSession :  Not a drm file so no need to open new decrypt session with drmScheme = 0
04-02 15:08:53.596 262-2879/? E/DrmManagerClientWrapperImpl: DrmManagerClientSubWrapper::DrmInitialization():mDecryptHandle initialization fails
04-02 15:08:53.596 262-2879/? E/DrmWrapper: DrmWrapper::isDrm(): This not null
04-02 15:08:53.596 262-2879/? E/DrmManagerClientWrapperImpl: DrmManagerClientSubWrapper::isDrmContent(): Null Drm Instance
04-02 15:08:53.606 330-330/? E/DxDrmPluginEngine: DxDrmFrameworkPlugin::getDecodeSession : decryptSession not found
04-02 15:08:53.606 330-330/? E/DxDrmPluginEngine: DxDrmFrameworkPlugin::onOpenDecryptSession :  Not a drm file so no need to open new decrypt session with drmScheme = 0
04-02 15:08:53.606 262-11884/? E/DataSource: mimeType - video/mp4
    newConfidence - 0.40
04-02 15:08:53.626 330-330/? E/DxDrmPluginEngine: DxDrmFrameworkPlugin::getDecodeSession : decryptSession not found
04-02 15:08:53.626 330-330/? E/DxDrmPluginEngine: DxDrmFrameworkPlugin::onOpenDecryptSession :  Not a drm file so no need to open new decrypt session with drmScheme = 0
04-02 15:08:53.626 262-11884/? E/DataSource: final mimeType - video/mp4
    final confidence - 0.40
04-02 15:08:54.686 262-769/? E/audio_hw_dolby: audio_extn_dolby_ds2_set_endpoint: Dolby set endpint :0x2
04-02 15:08:56.686 729-2831/? E/WifiStateMachine: WifiStateMachine CMD_START_SCAN source -2 txSuccessRate=52.90 rxSuccessRate=83.09 targetRoamBSSID=any RSSI=-59
04-02 15:09:16.686 729-2831/? E/WifiStateMachine: WifiStateMachine CMD_START_SCAN source -2 txSuccessRate=5.18 rxSuccessRate=35.52 targetRoamBSSID=any RSSI=-63
04-02 15:09:36.686 729-2831/? E/WifiStateMachine: WifiStateMachine CMD_START_SCAN source -2 txSuccessRate=5.14 rxSuccessRate=41.52 targetRoamBSSID=any RSSI=-61
04-02 15:09:56.696 729-2831/? E/WifiStateMachine: WifiStateMachine CMD_START_SCAN source -2 txSuccessRate=4.84 rxSuccessRate=34.30 targetRoamBSSID=any RSSI=-59
04-02 15:10:04.606 729-2831/? E/native: do suspend false
04-02 15:10:04.636 3032-3032/? E/wpa_supplicant: wpa_driver_nl80211_driver_cmd: failed to issue private commands
04-02 15:10:04.636 729-2831/? E/WifiStateMachine: Unexpected BatchedScanResults :null
04-02 15:10:04.636 3032-3032/? E/wpa_supplicant: wpa_driver_nl80211_driver_cmd: failed to issue private commands
04-02 15:10:05.076 729-2831/? E/WifiStateMachine: WifiStateMachine: Leaving Connected state
04-02 15:10:16.696 729-2831/? E/WifiStateMachine: WifiStateMachine CMD_START_SCAN source -2 txSuccessRate=2.13 rxSuccessRate=35.92 targetRoamBSSID=any RSSI=-60
    WifiStateMachine L2Connected CMD_START_SCAN source -2 171, 172 -> obsolete
04-02 15:10:25.096 729-2831/? E/WifiStateMachine: WifiStateMachine CMD_START_SCAN source -2 txSuccessRate=3.53 rxSuccessRate=37.23 targetRoamBSSID=any RSSI=-61
04-02 15:10:45.086 729-2831/? E/WifiStateMachine: WifiStateMachine CMD_START_SCAN source -2 txSuccessRate=4.28 rxSuccessRate=31.24 targetRoamBSSID=any RSSI=-63
```

---

I don't have a clear answer why and when this crash occurs, as sometimes application works just fine and `dtg/clear` directories are created.
I thought it's related to ```E/Vold: Failed to find mounted volume for /storage/sdcard1/Android/data/com.my.application.package/files/```, but this error occurs in logs even when there's no crash. 😐

**Comment by vgaidarji** [comment]
@noamtamim ok, finally I found what's the problem but I can't fully why it happens 🐛.
These are the stats from Fabric for the `mkdirs` crash:
image
It happens mostly on Android 5, but not only (which is super weird).
Luckily, I have Kyocera Hydro View, Android 5.1.1 where I was able to reproduce the issue and fix it. And I couldn't reproduce it on other Android 5.x devices 😶.

The issue is caused by missing explicit declaration of permissions:
```
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
``` 
Once I include these explicit permissions (and don't request/check them explicitly at runtime!), crash is not reproducible anymore.

[Official docs](https://developer.android.com/reference/android/Manifest.permission#WRITE_EXTERNAL_STORAGE) say these permissions are not required to be present in `AndroidManifest.xml` in following cases:
> Starting in API level 19, this permission is not required to read/write files in your application-specific directories returned by Context.getExternalFilesDir(String) and Context.getExternalCacheDir().

This is what I did to reproduce the crash:
**Before fix**
- install & open - no crash
- clear data & open - no crash
- re-install & open - **crash!!!**
- clear data & open - **crash!!!**. Keeps crashing until 5.
- reboot device & open - no crash

**After fix (explicit permissions in manifest)**
- install & open - no crash
- clear data & open - no crash
- re-install & open - no crash
- clear data & open - no crash
- reboot device & open - no crash

I noticed spikes of this `mkdirs` crash somewhere during first 1-2 weeks after each Android application release. This proves the theory that crash appears for users during re-install/update. And if users don't restart the device, application will be crashing always 😞.
I still don't have an answer why application works without issues on all Android versions, and crashes on some specific devices and explicit permissions fix the situation. Bug in Android ROM's on that devices? No idea!

----

I see that you have explicition permissions declaration in test `dtgapp` [here](https://github.com/kaltura/playkit-dtg-android/blob/6bcc89c0b7e96f6baa10c0dc5e5096de812eb8ac/dtgapp/src/main/AndroidManifest.xml#L6-L7), but not in `dtglib` [manifest](https://github.com/kaltura/playkit-dtg-android/blob/6bcc89c0b7e96f6baa10c0dc5e5096de812eb8ac/dtglib/src/main/AndroidManifest.xml#L5).
@noamtamim @giladna QQ: should `dtglib` have explicit declaration of `WRITE_EXTERNAL_STORAGE`/`READ_EXTERNAL_STORAGE` to avoid this crash on client applications.

**Comment by vgaidarji** [comment]
@noamtamim Follow up on `mkdirs` crash. Adding explicit permissions to `AndroidManifest.xml` helped significantly to reduce the number of crashes, but didn't fix it on 100%.

Here are the stats from Fabric from last 90 days for `mkdirs` crash:
screen shot 2018-09-12 at 11 36 52

As you can see crash occurrence reduced significantly. I would still consider it as a fix even if it's a partial success.
Stacktrace of the `mkdirs` crash is the same for new application with explicit permissions.
And the good thing that crash is not reproducible on Kyocera devices anymore.
I'll continue to monitor this crash and hope that one day I'll find a fix which will work for all other devices too. It should be definitely something device/custom OS specific.

**Comment by noamtamim** [comment]
Thank you @vgaidarji. In the next version I've changed the code so that instead of this crash you'll get an IOException when calling `ContentManager.start()` (when mkdirs() has failed). So, at least it's not a crash.

**Pull request closed without merging**
